from __future__ import annotations

from typing import Final

DOMAIN: Final = "cummins_gnr8r"
NAME: Final = "cummins_GNR8R"
VERSION: Final = "0.1.0"

PLATFORMS: Final = ("binary_sensor", "sensor")

DEFAULT_NAME: Final = "cummins_GNR8R"
DEFAULT_MANUFACTURER: Final = "Cummins"
DEFAULT_MODEL: Final = "QuietConnect Generator"
DEFAULT_MODBUS_MODEL: Final = "PowerCommand 2.x Generator"

BACKEND_ESPHOME_DISCRETE: Final = "esphome_discrete"
BACKEND_PCC1302_MODBUS: Final = "pcc1302_modbus"
BACKENDS: Final = (BACKEND_ESPHOME_DISCRETE, BACKEND_PCC1302_MODBUS)

CONF_BACKEND: Final = "backend"
CONF_UTILITY_AVAILABLE_ENTITY_ID: Final = "utility_available_entity_id"
CONF_ATS_ON_GENERATOR_ENTITY_ID: Final = "ats_on_generator_entity_id"
CONF_GENERATOR_RUNNING_ENTITY_ID: Final = "generator_running_entity_id"
CONF_GENERATOR_FAULT_ENTITY_ID: Final = "generator_fault_entity_id"
CONF_INVERT_UTILITY_AVAILABLE: Final = "invert_utility_available"
CONF_INVERT_ATS_ON_GENERATOR: Final = "invert_ats_on_generator"
CONF_INVERT_GENERATOR_RUNNING: Final = "invert_generator_running"
CONF_INVERT_GENERATOR_FAULT: Final = "invert_generator_fault"

CONF_POLL_INTERVAL: Final = "poll_interval"
CONF_SCAN_THROTTLE_MS: Final = "scan_throttle_ms"
CONF_SERIAL_PORT: Final = "serial_port"
CONF_SLAVE: Final = "slave"
CONF_BAUDRATE: Final = "baudrate"
CONF_BYTESIZE: Final = "bytesize"
CONF_PARITY: Final = "parity"
CONF_STOPBITS: Final = "stopbits"

DEFAULT_SLAVE: Final = 1
DEFAULT_BAUDRATE: Final = 9600
DEFAULT_BYTESIZE: Final = 8
DEFAULT_PARITY: Final = "N"
DEFAULT_STOPBITS: Final = 1
DEFAULT_POLL_INTERVAL: Final = 10
DEFAULT_SCAN_THROTTLE_MS: Final = 0
DEFAULT_TIMEOUT: Final = 2.0
DEFAULT_RETRIES: Final = 2

MIN_POLL_INTERVAL: Final = 5
MAX_POLL_INTERVAL: Final = 300

DATA_COORDINATOR: Final = "coordinator"
DATA_BACKEND: Final = "backend"

ROLE_UTILITY_AVAILABLE: Final = "utility_available"
ROLE_ATS_ON_GENERATOR: Final = "ats_on_generator"
ROLE_GENERATOR_RUNNING: Final = "generator_running"
ROLE_GENERATOR_FAULT: Final = "generator_fault"
LOGICAL_ROLES: Final = (
    ROLE_UTILITY_AVAILABLE,
    ROLE_ATS_ON_GENERATOR,
    ROLE_GENERATOR_RUNNING,
    ROLE_GENERATOR_FAULT,
)

DERIVED_RUNNING_ON_GENERATOR: Final = "running_on_generator"
DERIVED_UTILITY_OUTAGE_ACTIVE: Final = "utility_outage_active"
DERIVED_TRANSFER_IN_PROGRESS: Final = "transfer_in_progress"
STATE_TEXT_KEY: Final = "generator_system_state"
OPERATING_STATUS_KEY: Final = "generator_operating_status"
ACTION_REQUIRED_KEY: Final = "action_required"

MODBUS_REGISTER_NFPA_BITMAP: Final = 40716
MODBUS_REGISTER_EXTENDED_BITMAP: Final = 40717
MODBUS_REGISTER_BATTERY_VOLTAGE: Final = 40735
MODBUS_REGISTER_OIL_PRESSURE: Final = 40736
MODBUS_REGISTER_COOLANT_TEMPERATURE: Final = 40738
MODBUS_REGISTER_ENGINE_SPEED: Final = 40742
MODBUS_REGISTER_TOTAL_RUNS: Final = 40743
MODBUS_REGISTER_RUNTIME_HIGH: Final = 40744
MODBUS_REGISTER_RUNTIME_LOW: Final = 40745
MODBUS_REGISTER_FREQUENCY: Final = 40750
MODBUS_REGISTER_UTILITY_LN_AVERAGE_VOLTAGE: Final = 40062
MODBUS_REGISTER_UTILITY_FREQUENCY: Final = 40084
MODBUS_REGISTER_ATS1_DEVICE_TYPE: Final = 40257
MODBUS_REGISTER_ATS1_MODE: Final = 40258
MODBUS_REGISTER_ATS1_STATE: Final = 40259
MODBUS_REGISTER_ATS1_FAULT_CODE: Final = 40260
MODBUS_REGISTER_ATS1_FAULT_TYPE: Final = 40261
MODBUS_REGISTER_ATS1_NFPA_BITMAP: Final = 40264
MODBUS_REGISTER_ATS1_EXTENDED_BITMAP: Final = 40265
MODBUS_REGISTER_CURRENT_FAULT_CODE: Final = 40712
MODBUS_REGISTER_CURRENT_FAULT_TYPE: Final = 40713
MODBUS_REGISTER_GENSET_LOAD_PERCENT: Final = 40714
MODBUS_REGISTER_GENSET_TOTAL_KW: Final = 40715

ATTR_BACKEND: Final = "backend"
ATTR_SOURCE_ENTITY_IDS: Final = "source_entity_ids"
ATTR_INVERSION: Final = "inversion"
